# Generated by Django 3.0.14 on 2022-05-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frist_Dose', models.DateField(null=True)),
                ('Second_Dose', models.DateField(null=True)),
                ('Third_Dose', models.DateField(null=True)),
                ('Vaccine_status', models.CharField(max_length=150, null=True)),
                ('Covid_Test_Date', models.CharField(max_length=150, null=True)),
                ('Covid_Status', models.DateField(null=True)),
                ('hospital_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.Hospital')),
            ],
        ),
    ]
