# Generated by Django 3.0.14 on 2022-05-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccination_Info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination_info',
            name='Covid_Status',
        ),
        migrations.RemoveField(
            model_name='vaccination_info',
            name='Covid_Test_Date',
        ),
    ]
