# Generated by Django 3.0.14 on 2022-05-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
        ('Hospital', '0001_initial'),
        ('Vaccination_Info', '0002_auto_20220511_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('vaccination_info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Vaccination_Info.Vaccination_Info')),
                ('login_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Login.Login')),
                ('nid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=50)),
                ('flat_no', models.CharField(max_length=50)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('Covid_Test_Date', models.DateField(null=True)),
                ('Covid_Status', models.CharField(max_length=150, null=True)),
                ('Covid_Test_Hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.Hospital')),
            ],
            bases=('Login.login', 'Vaccination_Info.vaccination_info'),
        ),
    ]
