# Generated by Django 3.0.14 on 2022-05-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('confirmed', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
            ],
        ),
    ]
