# Generated by Django 3.0.14 on 2022-05-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('login_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Login.Login')),
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=200)),
                ('Number_of_Vaccine_Per_Day', models.IntegerField(default=0)),
                ('Vaccine', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('Seat_Capacity_For_COVID_Testing', models.IntegerField(default=0)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
            ],
            bases=('Login.login',),
        ),
    ]
